apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: redis-server
  labels:
    type: local
spec:
  storageClassName: longhorn
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: redis-server
    name: redis-pvc
  hostPath:
    path: "/mnt/data"
