unstable_features = true
comment_width = 100
condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
indent_style = "Visual"
imports_indent = "Visual"
max_width = 100
normalize_comments = false
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
struct_field_align_threshold = 30
enum_discrim_align_threshold = 30
use_field_init_shorthand = true
wrap_comments = true
imports_granularity = "Crate"
force_multiline_blocks = false
use_small_heuristics = "Max"
use_try_shorthand = true
