[package]
name = "handler"
version = "0.1.0"
authors = ["Volodia PAROL-GUARINO <volodia.parol-guarino@protonmail.com>"]
edition = "2021"

[dependencies]
hyper = {version = "0.14", features=["full"]}
tokio = {version = "1.17", features=["full"]}
futures = "0.3"
